// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.ximalaya.webgroup.tdkservice.netty.protocol.model;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface headerProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.headerProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 crcCode = 1;</code>
     */
    boolean hasCrcCode();
    /**
     * <code>required int32 crcCode = 1;</code>
     */
    int getCrcCode();

    /**
     * <code>required int32 length = 2;</code>
     */
    boolean hasLength();
    /**
     * <code>required int32 length = 2;</code>
     */
    int getLength();

    /**
     * <code>required int64 sessionID = 3;</code>
     */
    boolean hasSessionID();
    /**
     * <code>required int64 sessionID = 3;</code>
     */
    long getSessionID();

    /**
     * <code>required int32 type = 4;</code>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 4;</code>
     */
    int getType();

    /**
     * <code>required int32 priority = 5;</code>
     */
    boolean hasPriority();
    /**
     * <code>required int32 priority = 5;</code>
     */
    int getPriority();

    /**
     * <code>map&lt;string, string&gt; attachment = 6;</code>
     */
    int getAttachmentCount();
    /**
     * <code>map&lt;string, string&gt; attachment = 6;</code>
     */
    boolean containsAttachment(
        java.lang.String key);
    /**
     * Use {@link #getAttachmentMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getAttachment();
    /**
     * <code>map&lt;string, string&gt; attachment = 6;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getAttachmentMap();
    /**
     * <code>map&lt;string, string&gt; attachment = 6;</code>
     */

    java.lang.String getAttachmentOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; attachment = 6;</code>
     */

    java.lang.String getAttachmentOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code protocol.headerProto}
   */
  public  static final class headerProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.headerProto)
      headerProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use headerProto.newBuilder() to construct.
    private headerProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private headerProto() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private headerProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              crcCode_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              length_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              sessionID_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              type_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              priority_ = input.readInt32();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) != 0)) {
                attachment_ = com.google.protobuf.MapField.newMapField(
                    AttachmentDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000020;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              attachment__ = input.readMessage(
                  AttachmentDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              attachment_.getMutableMap().put(
                  attachment__.getKey(), attachment__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.internal_static_protocol_headerProto_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetAttachment();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.internal_static_protocol_headerProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto.class, com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto.Builder.class);
    }

    private int bitField0_;
    public static final int CRCCODE_FIELD_NUMBER = 1;
    private int crcCode_;
    /**
     * <code>required int32 crcCode = 1;</code>
     */
    public boolean hasCrcCode() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 crcCode = 1;</code>
     */
    public int getCrcCode() {
      return crcCode_;
    }

    public static final int LENGTH_FIELD_NUMBER = 2;
    private int length_;
    /**
     * <code>required int32 length = 2;</code>
     */
    public boolean hasLength() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 length = 2;</code>
     */
    public int getLength() {
      return length_;
    }

    public static final int SESSIONID_FIELD_NUMBER = 3;
    private long sessionID_;
    /**
     * <code>required int64 sessionID = 3;</code>
     */
    public boolean hasSessionID() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int64 sessionID = 3;</code>
     */
    public long getSessionID() {
      return sessionID_;
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <code>required int32 type = 4;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required int32 type = 4;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int PRIORITY_FIELD_NUMBER = 5;
    private int priority_;
    /**
     * <code>required int32 priority = 5;</code>
     */
    public boolean hasPriority() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required int32 priority = 5;</code>
     */
    public int getPriority() {
      return priority_;
    }

    public static final int ATTACHMENT_FIELD_NUMBER = 6;
    private static final class AttachmentDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.internal_static_protocol_headerProto_AttachmentEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> attachment_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetAttachment() {
      if (attachment_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AttachmentDefaultEntryHolder.defaultEntry);
      }
      return attachment_;
    }

    public int getAttachmentCount() {
      return internalGetAttachment().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; attachment = 6;</code>
     */

    public boolean containsAttachment(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetAttachment().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAttachmentMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAttachment() {
      return getAttachmentMap();
    }
    /**
     * <code>map&lt;string, string&gt; attachment = 6;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getAttachmentMap() {
      return internalGetAttachment().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; attachment = 6;</code>
     */

    public java.lang.String getAttachmentOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAttachment().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; attachment = 6;</code>
     */

    public java.lang.String getAttachmentOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAttachment().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCrcCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSessionID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPriority()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, crcCode_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, length_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt64(3, sessionID_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, type_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, priority_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetAttachment(),
          AttachmentDefaultEntryHolder.defaultEntry,
          6);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, crcCode_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, length_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, sessionID_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, type_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, priority_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetAttachment().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        attachment__ = AttachmentDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, attachment__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto)) {
        return super.equals(obj);
      }
      com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto other = (com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto) obj;

      if (hasCrcCode() != other.hasCrcCode()) return false;
      if (hasCrcCode()) {
        if (getCrcCode()
            != other.getCrcCode()) return false;
      }
      if (hasLength() != other.hasLength()) return false;
      if (hasLength()) {
        if (getLength()
            != other.getLength()) return false;
      }
      if (hasSessionID() != other.hasSessionID()) return false;
      if (hasSessionID()) {
        if (getSessionID()
            != other.getSessionID()) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (getType()
            != other.getType()) return false;
      }
      if (hasPriority() != other.hasPriority()) return false;
      if (hasPriority()) {
        if (getPriority()
            != other.getPriority()) return false;
      }
      if (!internalGetAttachment().equals(
          other.internalGetAttachment())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCrcCode()) {
        hash = (37 * hash) + CRCCODE_FIELD_NUMBER;
        hash = (53 * hash) + getCrcCode();
      }
      if (hasLength()) {
        hash = (37 * hash) + LENGTH_FIELD_NUMBER;
        hash = (53 * hash) + getLength();
      }
      if (hasSessionID()) {
        hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSessionID());
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType();
      }
      if (hasPriority()) {
        hash = (37 * hash) + PRIORITY_FIELD_NUMBER;
        hash = (53 * hash) + getPriority();
      }
      if (!internalGetAttachment().getMap().isEmpty()) {
        hash = (37 * hash) + ATTACHMENT_FIELD_NUMBER;
        hash = (53 * hash) + internalGetAttachment().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.headerProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.headerProto)
        com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.internal_static_protocol_headerProto_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetAttachment();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetMutableAttachment();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.internal_static_protocol_headerProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto.class, com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto.Builder.class);
      }

      // Construct using com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        crcCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        length_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        priority_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        internalGetMutableAttachment().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.internal_static_protocol_headerProto_descriptor;
      }

      @java.lang.Override
      public com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto getDefaultInstanceForType() {
        return com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto.getDefaultInstance();
      }

      @java.lang.Override
      public com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto build() {
        com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto buildPartial() {
        com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto result = new com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.crcCode_ = crcCode_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.length_ = length_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.sessionID_ = sessionID_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.type_ = type_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.priority_ = priority_;
          to_bitField0_ |= 0x00000010;
        }
        result.attachment_ = internalGetAttachment();
        result.attachment_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto) {
          return mergeFrom((com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto other) {
        if (other == com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto.getDefaultInstance()) return this;
        if (other.hasCrcCode()) {
          setCrcCode(other.getCrcCode());
        }
        if (other.hasLength()) {
          setLength(other.getLength());
        }
        if (other.hasSessionID()) {
          setSessionID(other.getSessionID());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasPriority()) {
          setPriority(other.getPriority());
        }
        internalGetMutableAttachment().mergeFrom(
            other.internalGetAttachment());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasCrcCode()) {
          return false;
        }
        if (!hasLength()) {
          return false;
        }
        if (!hasSessionID()) {
          return false;
        }
        if (!hasType()) {
          return false;
        }
        if (!hasPriority()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int crcCode_ ;
      /**
       * <code>required int32 crcCode = 1;</code>
       */
      public boolean hasCrcCode() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 crcCode = 1;</code>
       */
      public int getCrcCode() {
        return crcCode_;
      }
      /**
       * <code>required int32 crcCode = 1;</code>
       */
      public Builder setCrcCode(int value) {
        bitField0_ |= 0x00000001;
        crcCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 crcCode = 1;</code>
       */
      public Builder clearCrcCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        crcCode_ = 0;
        onChanged();
        return this;
      }

      private int length_ ;
      /**
       * <code>required int32 length = 2;</code>
       */
      public boolean hasLength() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 length = 2;</code>
       */
      public int getLength() {
        return length_;
      }
      /**
       * <code>required int32 length = 2;</code>
       */
      public Builder setLength(int value) {
        bitField0_ |= 0x00000002;
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 length = 2;</code>
       */
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000002);
        length_ = 0;
        onChanged();
        return this;
      }

      private long sessionID_ ;
      /**
       * <code>required int64 sessionID = 3;</code>
       */
      public boolean hasSessionID() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required int64 sessionID = 3;</code>
       */
      public long getSessionID() {
        return sessionID_;
      }
      /**
       * <code>required int64 sessionID = 3;</code>
       */
      public Builder setSessionID(long value) {
        bitField0_ |= 0x00000004;
        sessionID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 sessionID = 3;</code>
       */
      public Builder clearSessionID() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sessionID_ = 0L;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>required int32 type = 4;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required int32 type = 4;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 4;</code>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 4;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = 0;
        onChanged();
        return this;
      }

      private int priority_ ;
      /**
       * <code>required int32 priority = 5;</code>
       */
      public boolean hasPriority() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required int32 priority = 5;</code>
       */
      public int getPriority() {
        return priority_;
      }
      /**
       * <code>required int32 priority = 5;</code>
       */
      public Builder setPriority(int value) {
        bitField0_ |= 0x00000010;
        priority_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 priority = 5;</code>
       */
      public Builder clearPriority() {
        bitField0_ = (bitField0_ & ~0x00000010);
        priority_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> attachment_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetAttachment() {
        if (attachment_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              AttachmentDefaultEntryHolder.defaultEntry);
        }
        return attachment_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableAttachment() {
        onChanged();;
        if (attachment_ == null) {
          attachment_ = com.google.protobuf.MapField.newMapField(
              AttachmentDefaultEntryHolder.defaultEntry);
        }
        if (!attachment_.isMutable()) {
          attachment_ = attachment_.copy();
        }
        return attachment_;
      }

      public int getAttachmentCount() {
        return internalGetAttachment().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; attachment = 6;</code>
       */

      public boolean containsAttachment(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetAttachment().getMap().containsKey(key);
      }
      /**
       * Use {@link #getAttachmentMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getAttachment() {
        return getAttachmentMap();
      }
      /**
       * <code>map&lt;string, string&gt; attachment = 6;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getAttachmentMap() {
        return internalGetAttachment().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; attachment = 6;</code>
       */

      public java.lang.String getAttachmentOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAttachment().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; attachment = 6;</code>
       */

      public java.lang.String getAttachmentOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAttachment().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearAttachment() {
        internalGetMutableAttachment().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; attachment = 6;</code>
       */

      public Builder removeAttachment(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAttachment().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableAttachment() {
        return internalGetMutableAttachment().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; attachment = 6;</code>
       */
      public Builder putAttachment(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAttachment().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; attachment = 6;</code>
       */

      public Builder putAllAttachment(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableAttachment().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.headerProto)
    }

    // @@protoc_insertion_point(class_scope:protocol.headerProto)
    private static final com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto();
    }

    public static com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<headerProto>
        PARSER = new com.google.protobuf.AbstractParser<headerProto>() {
      @java.lang.Override
      public headerProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new headerProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<headerProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<headerProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface messageProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.messageProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .protocol.headerProto header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>required .protocol.headerProto header = 1;</code>
     */
    com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto getHeader();
    /**
     * <code>required .protocol.headerProto header = 1;</code>
     */
    com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProtoOrBuilder getHeaderOrBuilder();

    /**
     * <code>required string body = 2;</code>
     */
    boolean hasBody();
    /**
     * <code>required string body = 2;</code>
     */
    java.lang.String getBody();
    /**
     * <code>required string body = 2;</code>
     */
    com.google.protobuf.ByteString
        getBodyBytes();
  }
  /**
   * Protobuf type {@code protocol.messageProto}
   */
  public  static final class messageProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.messageProto)
      messageProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use messageProto.newBuilder() to construct.
    private messageProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private messageProto() {
      body_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private messageProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              body_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.internal_static_protocol_messageProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.internal_static_protocol_messageProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto.class, com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto.Builder.class);
    }

    private int bitField0_;
    public static final int HEADER_FIELD_NUMBER = 1;
    private com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto header_;
    /**
     * <code>required .protocol.headerProto header = 1;</code>
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .protocol.headerProto header = 1;</code>
     */
    public com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto getHeader() {
      return header_ == null ? com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto.getDefaultInstance() : header_;
    }
    /**
     * <code>required .protocol.headerProto header = 1;</code>
     */
    public com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProtoOrBuilder getHeaderOrBuilder() {
      return header_ == null ? com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto.getDefaultInstance() : header_;
    }

    public static final int BODY_FIELD_NUMBER = 2;
    private volatile java.lang.Object body_;
    /**
     * <code>required string body = 2;</code>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string body = 2;</code>
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          body_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string body = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBody()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHeader().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getHeader());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, body_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto)) {
        return super.equals(obj);
      }
      com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto other = (com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (hasBody() != other.hasBody()) return false;
      if (hasBody()) {
        if (!getBody()
            .equals(other.getBody())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.messageProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.messageProto)
        com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.internal_static_protocol_messageProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.internal_static_protocol_messageProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto.class, com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto.Builder.class);
      }

      // Construct using com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        body_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.internal_static_protocol_messageProto_descriptor;
      }

      @java.lang.Override
      public com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto getDefaultInstanceForType() {
        return com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto.getDefaultInstance();
      }

      @java.lang.Override
      public com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto build() {
        com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto buildPartial() {
        com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto result = new com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (headerBuilder_ == null) {
            result.header_ = header_;
          } else {
            result.header_ = headerBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.body_ = body_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto) {
          return mergeFrom((com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto other) {
        if (other == com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasBody()) {
          bitField0_ |= 0x00000002;
          body_ = other.body_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasHeader()) {
          return false;
        }
        if (!hasBody()) {
          return false;
        }
        if (!getHeader().isInitialized()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto header_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto, com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto.Builder, com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProtoOrBuilder> headerBuilder_;
      /**
       * <code>required .protocol.headerProto header = 1;</code>
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .protocol.headerProto header = 1;</code>
       */
      public com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>required .protocol.headerProto header = 1;</code>
       */
      public Builder setHeader(com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protocol.headerProto header = 1;</code>
       */
      public Builder setHeader(
          com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protocol.headerProto header = 1;</code>
       */
      public Builder mergeHeader(com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              header_ != null &&
              header_ != com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto.getDefaultInstance()) {
            header_ =
              com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protocol.headerProto header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .protocol.headerProto header = 1;</code>
       */
      public com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>required .protocol.headerProto header = 1;</code>
       */
      public com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProtoOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>required .protocol.headerProto header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto, com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto.Builder, com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProtoOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto, com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProto.Builder, com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.headerProtoOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private java.lang.Object body_ = "";
      /**
       * <code>required string body = 2;</code>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string body = 2;</code>
       */
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            body_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string body = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string body = 2;</code>
       */
      public Builder setBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string body = 2;</code>
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000002);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <code>required string body = 2;</code>
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        body_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.messageProto)
    }

    // @@protoc_insertion_point(class_scope:protocol.messageProto)
    private static final com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto();
    }

    public static com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<messageProto>
        PARSER = new com.google.protobuf.AbstractParser<messageProto>() {
      @java.lang.Override
      public messageProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new messageProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<messageProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<messageProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ximalaya.webgroup.tdkservice.netty.protocol.model.MessageProto.messageProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_headerProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_headerProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_headerProto_AttachmentEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_headerProto_AttachmentEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_messageProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_messageProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\022\010protocol\"\317\001\n\013headerProt" +
      "o\022\017\n\007crcCode\030\001 \002(\005\022\016\n\006length\030\002 \002(\005\022\021\n\tse" +
      "ssionID\030\003 \002(\003\022\014\n\004type\030\004 \002(\005\022\020\n\010priority\030" +
      "\005 \002(\005\0229\n\nattachment\030\006 \003(\0132%.protocol.hea" +
      "derProto.AttachmentEntry\0321\n\017AttachmentEn" +
      "try\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"C\n\014m" +
      "essageProto\022%\n\006header\030\001 \002(\0132\025.protocol.h" +
      "eaderProto\022\014\n\004body\030\002 \002(\tBE\n5com.ximalaya" +
      ".webgroup.tdkservice.netty.protocol.mode" +
      "lB\014MessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_headerProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_headerProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_headerProto_descriptor,
        new java.lang.String[] { "CrcCode", "Length", "SessionID", "Type", "Priority", "Attachment", });
    internal_static_protocol_headerProto_AttachmentEntry_descriptor =
      internal_static_protocol_headerProto_descriptor.getNestedTypes().get(0);
    internal_static_protocol_headerProto_AttachmentEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_headerProto_AttachmentEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_protocol_messageProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_messageProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_messageProto_descriptor,
        new java.lang.String[] { "Header", "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
